[package]
name = "maivin-replay"
description = "Maivin MCAP Replay"
repository = "https://bitbucket.org/au-zone/maivin-replay"
version = "0.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true
debug = false

[profile.profiling]
inherits = "release"
strip = false
debug = true

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.10"
zenoh = "0.10.1-rc"
cdr = "0.2.4"
clap = { version = "4.4.18", features = ["derive", "env"] }
edgefirst-schemas = "1.2.3"
log = { version = "0.4", features = ["release_max_level_debug"] }
env_logger = "0.11.2"
nix = { version = "0.28.0", features = ["time"] }
mcap = "0.9.2"
memmap2 = "0.9.4"
g2d-sys = {version = "1.0.0", path = "g2d-sys"}
videostream = "0.9.0"
dma-buf = "0.4.0"
dma-heap = "0.4.0"
turbojpeg = {version = "1.1.1", features = ["image"]}
ctrlc = "3.4.5"
tokio = { version = "1.41.1", features = ["rt"] }
